server:
  port: ${PORT:0}

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spotify-dev
    username: usr-spotify
    password: pwd-spotify
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    addresses: rabbitmq-container:5672
    virtual-host: music-app
    username: guest
    password: guest
  zipkin:
    base-url: http://zipkin-container:9411
    enabled: true
    sender:
      type: rabbit