server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 329295448206-qba1cktbpe5qargcg9ohegki337h7qj0.apps.googleusercontent.com
            client-secret: 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
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/google

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: apiMusic
          uri: lb://api-music
          predicates:
            - Path=/api/v1/musics/**
        - id: apiPlaylist
          uri: lb://api-playlist
          predicates:
            - Path=/api/v1/playlists/**